---
# Install libreswan package on every host.
- name: Install libreswan
  yum:
    name: libreswan
    state: present

- name: Enable IPSec Daemon
  service:
    name: ipsec
    enabled: yes

# Generate certificate authority for cluster.
- when: inventory_hostname == groups['masters'][0]
  static: no
  include: init-ipsec-ca.yml

# Create IPSec host certificate.
- when: inventory_hostname == groups['masters'][0]
  static: no
  include: init-ipsec-host-cert.yml
  with_items: "{{ play_hosts }}"
  loop_control:
    loop_var: ipsec_hostname

# Configure ipsec service on host
- include: init-ipsec-host.yml

# Create Connection policies
# This was for opportunistic IPSec, not used for non-opportunistic
- include: init-ipsec-host-connections.yml

# Openshift >= 3.7 default SHOULD BE firewalld
# Configure firewalld to permit IPsec communication
- include: firewalld-setup-rules.yml

# Ping nodes to establish node-to-node tunnels and verify IPSec tunnels
- include: ping-nodes.yml
